
#' Obstacle to travel
#'
#' Prevents travel along paths that cross through barriers or other obstacles that
#' cannot be traversed, like a river, a Greek phalanx, or
#' "[the Wall](https://en.wikipedia.org/wiki/World_of_A_Song_of_Ice_and_Fire#The_Wall)".
#'
#' @param x a cost `terrain` generated by `hf_terrain()`.
#' @param barrier an `sf` object.
#'
#' @return a `terrain` representing cost of travel.
#'
#' @export
#'
#' @examples
#' library(sf)
#' library(terra)
#'
#' fn <- system.file("extdata/red_butte_dem.tif", package = "hiker")
#' red_butte_dem <- rast(fn)
#'
#' fn <- system.file("extdata/red_butte_reservoir.geojson", package = "hiker")
#' red_butte_reservoir <- read_sf(fn)
#'
#' terrain <- hf_terrain(red_butte_dem)
#'
#' terrain <- hf_barrier(terrain, red_butte_reservoir)
#'
#' plot(terrain, main = "Travel Cost")
#' plot(st_geometry(red_butte_reservoir),
#'      col = NA,
#'      border = "red2",
#'      add = TRUE)
#'
hf_barrier <- function(x, barrier) {

  stop_if_not_terrain(x)

  stop_if_not_sf(barrier)

  stop_if_not_crs_equal(x$crs, barrier)

  rr <- terra::rast(
    nrow   = x$nrow,
    ncol   = x$ncol,
    extent = terra::ext(x$bb8),
    crs    = x$crs
  )

  barrier <- terra::vect(barrier)

  cells <- terra::cells(rr, barrier)[, 2]

  adj <- cbind(
    "from" = as.integer(x$conductance@i + 1),
    "to"   = as.integer(x$conductance@j + 1)
  )

  # find incident edges, from or to cells intersecting barrier
  i <- which(adj[, 1] %in% cells | adj[, 2] %in% cells)
  adj <- adj[i, ]

  x$conductance[adj] <- 0

  x <- update_range(x)

  return(x)

}
